version: "2.1"

services: 

 broker:
  build: ./broker
  ports:
    - "5672:5672"
  healthcheck:
    test: ["CMD", "./healthcheck.sh"]
    interval: 15s
    timeout: 5s
    retries: 5

 server:
  build: ./server
  depends_on:
    broker:
      condition: service_healthy
  
 client:
  build: ./client
  depends_on:
    broker:
      condition: service_healthy
